In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Ignore warnings :
import warnings
warnings.filterwarnings('ignore')


# Handle table-like data and matrices :
import numpy as np
import pandas as pd
import math



# Modelling Algorithms :

# Classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis , QuadraticDiscriminantAnalysis

# Regression
from sklearn.linear_model import LinearRegression,Ridge,Lasso,RidgeCV, ElasticNet
from sklearn.ensemble import RandomForestRegressor,BaggingRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import linear_model




# Modelling Helpers :
#from sklearn.preprocessing import Imputer , Normalizer , scale
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFECV
from sklearn.model_selection import GridSearchCV , KFold , cross_val_score



#preprocessing :
#from sklearn.preprocessing import MinMaxScaler , StandardScaler, Imputer, LabelEncoder



#evaluation metrics :

# Regression
from sklearn.metrics import mean_squared_log_error,mean_squared_error, r2_score,mean_absolute_error

# Classification
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score



In [ ]:
diamond_data = pd.read_csv("diamonds.csv")

In [ ]:
diamond_data = diamond_data.drop(["Unnamed: 0"],axis=1)
diamond_data.head()
print(diamond_data["price"])

0         326
1         326
2         327
3         334
4         335
         ... 
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64


In [ ]:
diamond_data[['x','y','z']] = diamond_data[['x','y','z']].replace(0,np.NaN)
diamond_data.dropna(inplace=True)

In [ ]:
one_hot_encoders_diamond_data =  pd.get_dummies(diamond_data)
cols = one_hot_encoders_diamond_data.columns
diamond_clean_data = pd.DataFrame(one_hot_encoders_diamond_data,columns= cols)
sc_X = StandardScaler()
numericals =  pd.DataFrame(sc_X.fit_transform(diamond_clean_data[['carat','depth','x','y','z','table']]),
                           columns=['carat','depth','x','y','z','table'],index=diamond_clean_data.index)

In [ ]:
diamond_clean_data_standard = diamond_clean_data.copy(deep=True)
diamond_clean_data_standard[['carat','depth','x','y','z','table']] = numericals[['carat','depth','x','y','z','table']]

In [ ]:
x = diamond_clean_data_standard.drop(["price"],axis=1)
y = diamond_clean_data_standard.price

train_x, test_x, train_y, test_y = train_test_split(x, y,random_state = 2,test_size=0.3)

In [ ]:
print(test_x.columns)

Index(['carat', 'depth', 'table', 'x', 'y', 'z', 'cut_Fair', 'cut_Good',
       'cut_Ideal', 'cut_Premium', 'cut_Very Good', 'color_D', 'color_E',
       'color_F', 'color_G', 'color_H', 'color_I', 'color_J', 'clarity_I1',
       'clarity_IF', 'clarity_SI1', 'clarity_SI2', 'clarity_VS1',
       'clarity_VS2', 'clarity_VVS1', 'clarity_VVS2'],
      dtype='object')


In [ ]:
zapros = str(input())
path = "output.csv"
with open(path, "w", newline='') as csvfile:
    csvfile.write('carat,cut,color,clarity,depth,table,x,y,z\n')
    csvfile.write(zapros+'\n')
print(zapros)

2.02,Premium,I,VS2,59.6,60,8.2,8.25,4.9
2.02,Premium,I,VS2,59.6,60,8.2,8.25,4.9


In [ ]:
a= pd.read_csv('output.csv')
print(a)

   carat      cut color clarity  depth  table    x     y    z
0   2.02  Premium     I     VS2   59.6     60  8.2  8.25  4.9


In [ ]:
data = pd.get_dummies(a)
print(data)

   carat  depth  table    x     y    z  cut_Premium  color_I  clarity_VS2
0   2.02   59.6     60  8.2  8.25  4.9            1        1            1


In [ ]:
d = {'carat':[0], 'depth':[0], 'table':[0], 'x':[0], 'y':[0], 'z': [0], 'cut_Fair':[0], 'cut_Good':[0], 'cut_Ideal':[0], 'cut_Premium':[0], 'cut_Very Good':[0], 'color_D':[0], 'color_E':[0], 'color_F':[0],'color_G':[0], 'color_H':[0], 'color_I':[0], 'color_J':[0], 'clarity_I1':[0], 'clarity_IF':[0], 'clarity_SI1':[0], 'clarity_SI2':[0], 'clarity_VS1':[0], 'clarity_VS2':[0], 'clarity_VVS1':[0], 'clarity_VVS2':[0]}

In [ ]:
for element in data.columns:
    d[element] = list(data[element])

print(d)

{'carat': [2.02], 'depth': [59.6], 'table': [60], 'x': [8.2], 'y': [8.25], 'z': [4.9], 'cut_Fair': [0], 'cut_Good': [0], 'cut_Ideal': [0], 'cut_Premium': [1], 'cut_Very Good': [0], 'color_D': [0], 'color_E': [0], 'color_F': [0], 'color_G': [0], 'color_H': [0], 'color_I': [1], 'color_J': [0], 'clarity_I1': [0], 'clarity_IF': [0], 'clarity_SI1': [0], 'clarity_SI2': [0], 'clarity_VS1': [0], 'clarity_VS2': [1], 'clarity_VVS1': [0], 'clarity_VVS2': [0]}


In [ ]:
s = pd.DataFrame.from_dict(d)
print(s)


   carat  depth  table  ...  clarity_VS2  clarity_VVS1  clarity_VVS2
0   2.02   59.6     60  ...            1             0             0

[1 rows x 26 columns]


In [ ]:
regr = linear_model.LinearRegression()
regr.fit(train_x,train_y)
y_pred = regr.predict(test_x)
print(y_pred)
print("accuracy: "+ str(regr.score(test_x,test_y)*100) + "%")
print("Mean absolute error: {}".format(mean_absolute_error(test_y,y_pred)))
print("Mean squared error: {}".format(mean_squared_error(test_y,y_pred)))
R2 = r2_score(test_y,y_pred)
print('R Squared: {}'.format(R2))
n=test_x.shape[0]
p=test_x.shape[1] - 1

adj_rsquared = 1 - (1 - R2) * ((n - 1)/(n-p-1))
print('Adjusted R Squared: {}'.format(adj_rsquared))

[ 129.18641384  356.67773315 3055.83157948 ... 5100.28446603 -796.19219526
  467.08057278]
accuracy: 92.21078518476793%
Mean absolute error: 731.4415989248855
Mean squared error: 1222201.224070932
R Squared: 0.9221078518476793
Adjusted R Squared: 0.9219872757669482


In [ ]:
y_pred = regr.predict(s)
print(y_pred)

[-3845.54926391]


In [ ]:
clf_la = Lasso(normalize=True)
clf_la.fit(train_x,train_y)
y_pred = clf_la.predict(test_x)
print('')
print('###### Lasso Regression ######')
print('Score : %.4f' % clf_la.score(test_x, test_y))

mse = mean_squared_error(test_y, y_pred)
mae = mean_absolute_error(test_y, y_pred)
rmse = mean_squared_error(test_y, y_pred)**0.5
r2 = r2_score(test_y, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)


###### Lasso Regression ######
Score : 0.8782

MSE    : 1911827.63 
MAE    : 869.21 
RMSE   : 1382.69 
R2     : 0.88 


In [ ]:
y_pred = clf_la.predict(s)
print(y_pred)

[11461.11145006]


In [ ]:
clf_ar = AdaBoostRegressor(n_estimators=1000)
clf_ar.fit(train_x , train_y)
accuracies = cross_val_score(estimator = clf_ar, X = train_x, y = train_y, cv = 5,verbose = 1)
y_pred = clf_ar.predict(test_x)
print('')
print('###### AdaBoost Regression ######')
print('Score : %.4f' % clf_ar.score(test_x, test_y))
print(accuracies)

mse = mean_squared_error(test_y, y_pred)
mae = mean_absolute_error(test_y, y_pred)
rmse = mean_squared_error(test_y, y_pred)**0.5
r2 = r2_score(test_y, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.2min finished



###### AdaBoost Regression ######
Score : 0.8227
[0.61044017 0.85804965 0.87516819 0.88368744 0.88332175]

MSE    : 2781576.30 
MAE    : 1415.72 
RMSE   : 1667.81 
R2     : 0.82 


In [ ]:
y_pred = clf_ar.predict(s)
print(y_pred)

[13757.7295829]


In [ ]:
clf_rr = Ridge(normalize=True)
clf_rr.fit(train_x , train_y)
accuracies = cross_val_score(estimator = clf_rr, X = train_x, y = train_y, cv = 5,verbose = 1)
y_pred = clf_rr.predict(test_x)
print('')
print('###### Ridge Regression ######')
print('Score : %.4f' % clf_rr.score(test_x, test_y))
print(accuracies)

mse = mean_squared_error(test_y, y_pred)
mae = mean_absolute_error(test_y, y_pred)
rmse = mean_squared_error(test_y, y_pred)**0.5
r2 = r2_score(test_y, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.2s finished



###### Ridge Regression ######
Score : 0.8039
[0.80465751 0.80082824 0.79616859 0.80014069 0.80416299]

MSE    : 3077274.32 
MAE    : 1125.40 
RMSE   : 1754.22 
R2     : 0.80 


In [ ]:
y_pred = clf_rr.predict(s)
print(y_pred)

[20799.82665121]


In [ ]:
clf_gbr = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,max_depth=1, random_state=0, loss='ls',verbose = 1)
clf_gbr.fit(train_x , train_y)
accuracies = cross_val_score(estimator = clf_gbr, X = train_x, y = train_y, cv = 5,verbose = 1)
y_pred = clf_gbr.predict(test_x)
print('')
print('###### Gradient Boosting Regression #######')
print('Score : %.4f' % clf_gbr.score(test_x, test_y))
print(accuracies)

mse = mean_squared_error(test_y, y_pred)
mae = mean_absolute_error(test_y, y_pred)
rmse = mean_squared_error(test_y, y_pred)**0.5
r2 = r2_score(test_y, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)

      Iter       Train Loss   Remaining Time 
         1    14141267.1496            2.13s
         2    12530790.6914            2.14s
         3    11197448.0422            2.08s
         4    10005941.2794            2.06s
         5     9029948.2640            2.03s
         6     8173690.0904            2.00s
         7     7406538.2029            1.96s
         8     6770697.1978            1.94s
         9     6203717.1336            1.92s
        10     5729574.1928            1.92s
        20     3175757.7962            1.69s
        30     2361288.9242            1.49s
        40     2074618.0131            1.27s
        50     1917170.4175            1.06s
        60     1800295.2274            0.84s
        70     1711099.5470            0.63s
        80     1638073.2563            0.42s
        90     1575664.8535            0.21s
       100     1522174.8444            0.00s
      Iter       Train Loss   Remaining Time 
         1    14097289.8163            1.62s
        

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


        20     3145901.4737            1.35s
        30     2337224.7671            1.18s
        40     2053096.1169            1.01s
        50     1897420.8367            0.84s
        60     1781740.8160            0.67s
        70     1693521.5136            0.50s
        80     1621454.5728            0.33s
        90     1559768.0402            0.16s
       100     1506524.1552            0.00s
      Iter       Train Loss   Remaining Time 
         1    14189191.5732            1.98s
         2    12575804.7007            1.75s
         3    11239311.2679            1.67s
         4    10042565.6008            1.64s
         5     9062662.5181            1.61s
         6     8203863.4458            1.57s
         7     7433632.9918            1.58s
         8     6795411.5824            1.58s
         9     6226202.9411            1.54s
        10     5751559.8093            1.52s
        20     3191514.2231            1.31s
        30     2379357.3750            1.12s
        4

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    8.8s finished


In [ ]:
y_pred = clf_gbr.predict(s)
print(y_pred)

[14551.88383756]


In [ ]:
clf_rf = RandomForestRegressor()
clf_rf.fit(train_x , train_y)
accuracies = cross_val_score(estimator = clf_rf, X = train_x, y = train_y, cv = 5,verbose = 1)
y_pred = clf_rf.predict(test_x)
print('')
print('###### Random Forest ######')
print('Score : %.4f' % clf_rf.score(test_x, test_y))
print(accuracies)

mse = mean_squared_error(test_y, y_pred)
mae = mean_absolute_error(test_y, y_pred)
rmse = mean_squared_error(test_y, y_pred)**0.5
r2 = r2_score(test_y, y_pred)

print('')
print('MSE    : %0.2f ' % mse)
print('MAE    : %0.2f ' % mae)
print('RMSE   : %0.2f ' % rmse)
print('R2     : %0.2f ' % r2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.6min finished



###### Random Forest ######
Score : 0.9800
[0.97935371 0.98185141 0.97984147 0.98166463 0.98077532]

MSE    : 314301.80 
MAE    : 279.01 
RMSE   : 560.63 
R2     : 0.98 


In [ ]:
y_pred = clf_rf.predict(s)
print(y_pred)

[15810.99]
